### ISSUE TITLE
AccessLint CI failing in CircleCI

### ISSUE THREAD

**Issue by tysongach** [accesslint/accesslint-ci#29]
```
bundle exec middleman server --daemon --port=4567 --watcher-disable && \
accesslint-ci scan http://localhost:4567
== The Middleman is loading
== Preferring use of LibSass
== LiveReload accepting connections from ws://10.0.4.1:35729
== View your site at "http://localhost:4567", "http://127.0.0.1:4567"
== Inspect your site configuration at "http://localhost:4567/__middleman", "http://127.0.0.1:4567/__middleman"
== Middleman preview server is running in background with PID 16390
/home/ubuntu/.rvm/gems/ruby-2.3.1/gems/accesslint-ci-0.1.10/lib/accesslint/ci/commenter.rb:40:in `pull_request_number': undefined method `[]' for nil:NilClass (NoMethodError)
	from /home/ubuntu/.rvm/gems/ruby-2.3.1/gems/accesslint-ci-0.1.10/lib/accesslint/ci/commenter.rb:23:in `github_uri'
	from /home/ubuntu/.rvm/gems/ruby-2.3.1/gems/accesslint-ci-0.1.10/lib/accesslint/ci/commenter.rb:15:in `perform'
	from /home/ubuntu/.rvm/gems/ruby-2.3.1/gems/accesslint-ci-0.1.10/lib/accesslint/ci/commenter.rb:7:in `perform'
	from /home/ubuntu/.rvm/gems/ruby-2.3.1/gems/accesslint-ci-0.1.10/lib/accesslint/ci/cli.rb:17:in `scan'
	from /home/ubuntu/.rvm/gems/ruby-2.3.1/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
	from /home/ubuntu/.rvm/gems/ruby-2.3.1/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
	from /home/ubuntu/.rvm/gems/ruby-2.3.1/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
	from /home/ubuntu/.rvm/gems/ruby-2.3.1/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
	from /home/ubuntu/.rvm/gems/ruby-2.3.1/gems/accesslint-ci-0.1.10/bin/accesslint-ci:4:in `<top (required)>'
	from /home/ubuntu/.rvm/gems/ruby-2.3.1/bin/accesslint-ci:23:in `load'
	from /home/ubuntu/.rvm/gems/ruby-2.3.1/bin/accesslint-ci:23:in `<main>'
	from /home/ubuntu/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `eval'
	from /home/ubuntu/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `<main>'

bundle exec middleman server --daemon --port=4567 --watcher-disable && \
accesslint-ci scan http://localhost:4567
 returned exit code 1
```

**Comment by ckundo** [comment]
@tysongach I'm investigating this, I think there's a case where an environment variable exists in CI, but is blank.
