### ISSUE TITLE
Listen error with accesslint + middleman

### ISSUE THREAD

**Issue by joaocunha** [accesslint/accesslint-ci#30]
Running accesslint on my middleman server raises a listen error. The task gets stuck.

Ruby 2.3.3
Middleman 4.1.14
Accesslint 0.1.10

```
accesslint-ci scan --skip-ci http://localhost:4567/landing-page.html
```

```
E, [2016-12-08T04:47:39.764190 #4369] ERROR -- : fsevent: running worker failed: different prefix: "" and "/Users/myuser/Sites/vinyl":/Users/myuser/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/pathname.rb:520:in `relative_path_from'
/Users/myuser/.rvm/gems/ruby-2.3.3/gems/listen-3.0.8/lib/listen/adapter/darwin.rb:61:in `block in _process_event'
/Users/myuser/.rvm/gems/ruby-2.3.3/gems/listen-3.0.8/lib/listen/adapter/darwin.rb:57:in `each'
/Users/myuser/.rvm/gems/ruby-2.3.3/gems/listen-3.0.8/lib/listen/adapter/darwin.rb:57:in `_process_event'
/Users/myuser/.rvm/gems/ruby-2.3.3/gems/listen-3.0.8/lib/listen/adapter/base.rb:42:in `block (2 levels) in configure'
/Users/myuser/.rvm/gems/ruby-2.3.3/gems/rb-fsevent-0.9.8/lib/rb-fsevent/fsevent.rb:45:in `run'
/Users/myuser/.rvm/gems/ruby-2.3.3/gems/listen-3.0.8/lib/listen/adapter/darwin.rb:68:in `_run_worker'
/Users/myuser/.rvm/gems/ruby-2.3.3/gems/listen-3.0.8/lib/listen/adapter/darwin.rb:52:in `_run'
/Users/myuser/.rvm/gems/ruby-2.3.3/gems/listen-3.0.8/lib/listen/adapter/base.rb:78:in `block in start'
/Users/myuser/.rvm/gems/ruby-2.3.3/gems/listen-3.0.8/lib/listen/internals/thread_pool.rb:6:in `block in add' called from: /Users/myuser/.rvm/gems/ruby-2.3.3/gems/listen-3.0.8/lib/listen/adapter/darwin.rb:67:in `_run_worker'
/Users/myuser/.rvm/gems/ruby-2.3.3/gems/listen-3.0.8/lib/listen/adapter/darwin.rb:52:in `_run'
/Users/myuser/.rvm/gems/ruby-2.3.3/gems/listen-3.0.8/lib/listen/adapter/base.rb:78:in `block in start'
/Users/myuser/.rvm/gems/ruby-2.3.3/gems/listen-3.0.8/lib/listen/internals/thread_pool.rb:6:in `block in add'
```

**Comment by ckundo** [comment]
@joaocunha what command are you using to run your middleman server? You may need to turn of watchers.

**Comment by joaocunha** [comment]
@ckundo plain `middleman`, but it has an external pipeline full of Gulp stuff.

This is the config file:

```
lib = File.expand_path('../lib', __FILE__)
$LOAD_PATH.unshift(lib) unless $LOAD_PATH.include?(lib)

require 'inline_svg'
require 'pry'

require 'config/source_watcher'
require 'config/inline_svg'
require 'config/middlewares/locale_from_param_middleware'

require 'vinyl'

use LocaleFromParamMiddleware

page '/*.xml', layout: false
page '/*.json', layout: false
page '/*.txt', layout: false

ignore 'partials/**/*'

activate :i18n, templates_dir: '.', data: 'config/locales', mount_at_root: :en

helpers Vinyl::ViewHelpers
helpers InlineSvg::ActionView::Helpers

set :slim, { pretty: true, format: :html }

activate :external_pipeline,
  name: :gulp,
  command: "yarn run gulp #{build? ? :build : :serve}",
  source: 'dist',
  latency: 2
```

**Comment by ckundo** [comment]
@joaocunha please try running middleman with the `--watcher-disable` flag, as shown here: https://github.com/thoughtbot/bourbon.io/blob/master/circle.yml#L17

**Comment by tysongach** [comment]
@joaocunha 👋  Did running the server with `--watcher-disable` resolve the issue? Can this be closed?
